//export const MONGO_URI =  `mongodb+srv://${process.env.MONGO_USER_NAME}:${process.env.MONGO_USER_PASSWORD}@cluster0.bavoa.mongodb.net/?retryWrites=true&w=majority`
//export const MONGO_URI = `mongodb://mongo:123@localhost:27017/`;
export const MONGO_USER_NAME = 'saikatdey2100';
export const MONGO_USER_PASSWORD = '0LGOa4J0uhKotzbS';
export const MONGO_URI = `mongodb+srv://${MONGO_USER_NAME}:${MONGO_USER_PASSWORD}@emerald-cluster.qszztjn.mongodb.net/`;
export const AWS_S3_BUCKET = 'emerald-city';
export const AWS_S3_REGION = 'ap-south-1';
export const DB_NAME = 'emerald';
export const AWS_ACCESS_KEY_ID = 'AKIA534SVJVTZHDW4AVZ';
export const AWS_SECRET_ACCESS_KEY = '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';
